### ISSUE TITLE
MAPA_MENTAL_FELIX

### ISSUE THREAD

**Issue by Felix-Angel** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Felix-Angel#2]
[MAPA_MENTAL_FUNCIONES_CONJUNTOS Y RELACIONES_FELIX.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Felix-Angel/files/12679573/MAPA_MENTAL_FUNCIONES_CONJUNTOS.Y.RELACIONES_FELIX.pdf)

**Comment by 23620031** [comment]
MANEJO CONCEPTUAL Y DOMINIO DEL TEMA-> 25/25
RELACIÓN ENTRE LOS CONCEPTOS EN EL MAPA-> 25/25
CALIDAD DE LA PRESENTACIÓN-> 25/25
JERARQUIZACIÓN DE IDEAS-> 25/25

TOTAL=20/20

CALIFICADO POR EL EQUIPO DE LÓPEZ DOMÍNGUEZ

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
